name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      uses: actions/checkout@v3
      working-directory: ./source
      run: make -C source
      
